App\Entity\ExternalService:
    type: entity
    table: external_service
    uniqueConstraints:
        uniq_external_service_username_canonical:
            columns:
                - username_canonical
        uniq_external_service_email_canonical:
            columns:
                - email_canonical
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        locked:
            type: boolean
            nullable: false
        expired:
            type: boolean
            nullable: false
        expiresAt:
            type: datetime
            nullable: true
            column: expires_at
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        credentialsExpired:
            type: boolean
            nullable: false
            column: credentials_expired
        credentialsExpireAt:
            type: datetime
            nullable: true
            column: credentials_expire_at
        apikey:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        ip:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
