App\Entity\MailJob:
    type: entity
    table: mail_job
    indexes:
        idx_e7c3cf92b665eda0:
            columns:
                - mail_job_status_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        subject:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        senderEmail:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: sender_email
        bodyData:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
            column: body_data
        template:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    manyToOne:
        mailJobStatus:
            targetEntity: MailJobStatus
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                mail_job_status_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
